name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
